import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });
export const dynamic = 'force-dynamic'
export const fetchCache = 'force-no-store'
export const revalidate = 1000;

export const metadata: Metadata = {
  title: "Search Data | Fallout PnP Project",
  description: "Generated by create next app",
};

export default function SearchLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (

    <>
    
      {children}
    
    </>

  )

}
